pls live

AndroidManifest.xml
AudioListAdapter.java
AudioPlayerActivity.java
AudioSignal.java
res\layout\playlist.xml
res\layout\playlist_item.xml
res\values\dimens.xml
res\values\strings.xml
res\values\styles.xml
res\anim\grow_color.xml
res\anim\shrink_color.xml
res\anim\simple_grow.xml
res\anim\simple_shrink.xml
res\drawable-hdpi\search.png
res\drawable-mdpi\search.png
res\drawable-xhdpi\search.png
res\drawable-xxhdpi\search.png
res\drawable\back.png
res\drawable\backword.png
res\drawable\border_shadow.xml
res\drawable\down.png
res\drawable\edittext_bg.xml
res\drawable\forward.png
res\drawable\gradient.xml
res\drawable\image_border.xml
res\drawable\image_border_big.xml
res\drawable\mini_cart.png
res\drawable\next_mini.png
res\drawable\pause.png
res\drawable\pause_mini.png
res\drawable\play_big.png
res\drawable\play_mini.png
res\drawable\seekbar_progress.xml
res\drawable\seekbar_style.xml
res\drawable\share.png
res\layout-normal
res\layout-normal\activity_audio_player_new.xml
res\layout-normal\player.xml
res\layout-normal\player_widget.xml
res\layout-normal\playlist.xml
res\layout-normal\playlist_listitem.xml
res\values-land
res\values-land\dimens.xml
res\values-sw600dp
res\values-sw600dp\dimens.xml